/* integration.js for custom theme itegration
   DO NOT EDIT THIS FILE*/
/*   _     _            ____
    / \   (_) __ ___  _|  _ \ _ __ ___
   / _ \  | |/ _` \ \/ / |_) | '__/ _ \
  / ___ \ | | (_| |>  <|  __/| | | (_) |
 /_/   \_\/ |\__,_/_/\_\_|   |_|  \___/
        |__/
*/