<div class="page-title">
    <h1><?php echo $this->__('Shopping Cart is Empty') ?></h1>
</div>
<div class="cart-empty">
    <?php // echo $this->getChildHtml('checkout_cart_empty_widget'); ?>
    <p><?php echo $this->__('You have no items in your shopping cart.') ?></p>
    <p><?php echo $this->__('Click <a onclick="%s">here</a> to continue shopping.', 'AjaxPro.message.hide();return false;') ?></p>
    <?php // echo $this->getChildHtml('shopping.cart.table.after'); ?>
</div>
